name: LSIF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-go:latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir lsif_index
      - name: Generate LSIF data
        run: lsif-go -o lsif_index/index.lsif
      - name: Publish LSIF
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: lsif-index
          FOLDER: lsif_index
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}